name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: propeller-heads/ci-cd-templates/.github/workflows/release.yaml@main
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

  build-and-push:
    needs:
      - release
    if: needs.release.outputs.next_release_version != ''
    uses: propeller-heads/ci-cd-templates/.github/workflows/build-and-push-docker-image.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      image_tag: "${{ needs.release.outputs.next_release_version }}"
      image_name: tycho-indexer

  deploy-dev:
    needs:
      - release
      - build-and-push
    if: ${{ needs.release.outputs.next_release_version != '' }}
    uses: propeller-heads/ci-cd-templates/.github/workflows/deploy-dev.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      image_tag: "${{ needs.release.outputs.next_release_version }}"
      image_name: tycho-indexer
      app_name: tycho-indexer
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
